openapi: 3.0.0
info:
  title: Traffic API
  version: 1.0.0
  description: A simple API to fetch Traffic information for a specific city
servers:
  - url: http://localhost:3000/api
    description: Local server
paths:
  /Traffic/{city}:
    get:
      summary: Get Traffic data for a city
      description: Fetches Traffic data for the specified city.
      parameters:
        - in: path
          name: city
          required: true
          schema:
            type: string
          description: City for which to fetch the Traffic
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Traffic:
                    type: number
                    description: Current Traffic.
                    example: 20
                  rain:
                    type: number
                    description: Current rain.
                  wind:
                    type: number
                    description: Current wind.
                  rain:
                    type: number
                    description: Current rain.
        '404':
          description: City not found
        '500':
          description: Server error
